import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

live_config_reload = true

[window]
decorations = "Full"
opacity = 0.69
title = "Terminal"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMonoNerdFont" }
italic = { family = "JetBrainsMonoNerdFont"}
bold = { family = "JetBrainsMonoNerdFont"}
size = 14

[mouse]
hide_when_typing = true
