["nvim"]
target_path = "~/.config/nvim"

[".tmux.conf"]
target_path = "~/.tmux.conf"

["zsh/.oh-my-zsh/custom"]
target_path = "~/.oh-my-zsh/custom"

["zsh/.zshrc"]
target_path = "~/.zshrc"

["alacritty"]
target_path = "~/.config/alacritty"

["icons"]
target_path = "~/.icons"

["themes"]
target_path = "~/.themes"

["fonts"]
target_path = "~/.fonts"
