wallpaper {
    monitor = DP-3
    path = /home/olli/Downloads/cityscape.jpg
}

wallpaper {
    monitor = DP-2
    path = /home/olli/Downloads/cityscape.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/olli/Downloads/cityscape.jpg
}
