preload = /home/olli/Downloads/cityscape.jpg
wallpaper = DP-3, /home/olli/Downloads/cityscape.jpg
wallpaper = DP-2, /home/olli/Downloads/cityscape.jpg
wallpaper = HDMI-A-1, /home/olli/Downloads/cityscape.jpg
